### ISSUE TITLE
Error in library(recount3) : there is no package called ‘recount3’

### ISSUE THREAD

**Issue by ktavabi** [nih-cfde/training-rstudio-binder#2]
The R-notebook `recount3.md` [ln15](https://github.com/nih-cfde/training-rstudio-binder/blob/7fa7ee8854e3012f5bea9d7f7b0fa3b0aaefe3f3/GTEx/scripts/recount3.Rmd#L15)  throws missing library error.

**Comment by ktavabi** [comment]
S

**Comment by raynamharris** [comment]
Thanks Kam! I added the install commands for users who need to install any of the required packages.
